backup-settings: only mount data partition if required

diff --git a/backup-settings b/backup-settings
--- a/backup-settings
+++ b/backup-settings
@@ -24,7 +24,9 @@ assert_rescue_mode
 create_workspace
 
 safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" -o ro || abort "Failed to mount root filesystem"
-safe_mount "${DATA_PARTITION}" "${DATA_MOUNTPOINT}" || abort "Failed to mount data filesystem"
+if is_beneath_directory "${FILENAME}" "${DATA_MOUNTPOINT}"; then
+	safe_mount "${DATA_PARTITION}" "${DATA_MOUNTPOINT}" || abort "Failed to mount data filesystem"
+fi
 
 mkdir -p backup-lists.d tmp/.recovery
 cd "${ROOT_MOUNTPOINT}"
