flash-kernel: take multiple colon-separated arc images with option -a, remove -l

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -7,7 +7,7 @@ set -e
 
 DEVICE=/dev/mmcblk0
 MEM_SIZE=0x20000000
-LCD_ANIM=/usr/share/fastboot/lcd_anim.bin
+ARC_IMAGES=/usr/share/fastboot/lcd_anim.bin:/usr/share/fastboot/fpga_load.bin
 MAX_IMAGE_SIZE=$((32 * 1024 * 1024))
 OPTION=A
 VMLINUX=
@@ -86,9 +86,16 @@ prepare_workspace()
 create_blob()
 {
 	ARGS="-m ${MEM_SIZE} -o ${1}"
-	if is_readable_file "${LCD_ANIM}"; then
-		ARGS="${ARGS} -f ${LCD_ANIM} -t arc -i 1"
-	fi
+	INDEX=0
+	OLDIFS=${IFS}
+	IFS=:
+	for FILE in ${ARC_IMAGES}; do
+		if is_readable_file "${FILE}"; then
+			ARGS="${ARGS} -f ${FILE} -t arc -i ${INDEX}"
+			INDEX=$((${INDEX} + 1))
+		fi
+	done
+	IFS=${OLDIFS}
 	if is_readable_file "${INITRD}"; then
 		ARGS="${ARGS} -f ${INITRD} -t initrd"
 	fi
@@ -125,13 +132,16 @@ select_boot_source()
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-c <cmdline>] [-d <device>] [-i <initrd>] [-l <lcd-bin>] [-m <mem-size>] [-o A|B] <vmlinux.bin>"
-	echo "       Default: -d ${DEVICE} -l ${LCD_ANIM} -m ${MEM_SIZE} -o ${OPTION}"
+	echo "Usage: ${0} [-hqtv] [-a <arc images>] [-c <cmdline>] [-d <device>] [-i <initrd>] [-m <mem-size>] [-o A|B] <vmlinux.bin>"
+	echo "       Default: -a ${ARC_IMAGES} -d ${DEVICE} -m ${MEM_SIZE} -o ${OPTION}"
 	exit ${1}
 }
 
-while getopts c:d:hi:l:m:o:qtv opt; do
+while getopts a:c:d:hi:m:o:qtv opt; do
 	case "${opt}" in
+		a)
+			ARC_IMAGES="${OPTARG}"
+			;;
 		c)
 			CMDLINE="${OPTARG}"
 			;;
@@ -140,9 +150,6 @@ while getopts c:d:hi:l:m:o:qtv opt; do
 			;;
 		i)
 			INITRD="${OPTARG}"
-			;;
-		l)
-			LCD_ANIM="${OPTARG}"
 			;;
 		m)
 			MEM_SIZE="${OPTARG}"
@@ -174,7 +181,12 @@ shift $((${OPTIND} - 1))
 VMLINUX="${1}"
 
 is_writeable_blockdev "${DEVICE}" || abort "Target block device '${DEVICE}' is not a writeable block device"
-is_empty "${LCD_ANIM}" || is_readable_file "${LCD_ANIM}" || abort "Cannot access '${LCD_ANIM}'"
+OLDIFS=${IFS}
+IFS=:
+for FILE in ${ARC_IMAGES}; do
+	is_readable_file "${FILE}" || abort "Cannot access '${FILE}'"
+done
+IFS=${OLDIFS}
 is_empty "${INITRD}" || is_readable_file "${INITRD}" || abort "Cannot access '${INITRD}'"
 ! is_empty "${VMLINUX}" || abort "No kernel image given"
 is_readable_file "${VMLINUX}" || abort "Cannot access '${VMLINUX}'"
