flash-tarball/backup-settings: fix handling when partitions are broken - we might have no root, use local tmp then - don't abort flashing/backup when dreambox-data is unmountable - don't abort when root cannot be unmounted, it might have not been mounted at all, an abort will happen when trying to repartitioning

diff --git a/flash-tarball b/flash-tarball
--- a/flash-tarball
+++ b/flash-tarball
@@ -72,7 +72,7 @@ if blkdev_has_filesystem "${ROOT_PARTITION}" || is_chardev "${ROOT_PARTITION}"; 
 fi
 [ "${RESTORE_SETTINGS}" = ":" -o -f "${SETTINGS}" ] || abort "Can't restore settings without prior backup!"
 
-unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem!"
 
 if $GPT_RECREATE || ! is_blockdev "${ROOT_PARTITION}" || ! blkdev_has_filesystem "${DATA_PARTITION}"; then
 	if is_beneath_directory "${FILENAME}" "${DATA_MOUNTPOINT}"; then
