treewide: move common functions to librecovery

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -3,9 +3,8 @@
 # Copyright (C) 2014 Dream Property GmbH
 #
 
-set -e
+source librecovery
 
-DEVICE=/dev/mmcblk0
 MEM_SIZE=0x10000000
 ARC_IMAGES=/usr/share/fastboot/lcd_anim.bin
 MAX_IMAGE_SIZE=$((32 * 1024 * 1024))
@@ -14,80 +13,10 @@ VMLINUX=
 CMDLINE=
 INITRD=
 
-STDOUT=/dev/null
-TEMP=
-VERBOSE=1
-
-is_blockdev()
-{
-	[ -b "${1}" ]
-}
-
-is_file()
-{
-	[ -f "${1}" ]
-}
-
-is_readable()
-{
-	[ -r "${1}" ]
-}
-
-is_readable_file()
-{
-	is_file "${1}" && is_readable "${1}"
-}
-
-is_writeable()
-{
-	[ -w "${1}" ]
-}
-
-is_writeable_blockdev()
-{
-	is_blockdev "${1}" && is_writeable "${1}"
-}
-
-is_empty()
-{
-	[ -z "${1}" ]
-}
-
-is_file_size_le()
-{
-	[ "`stat -c '%s' ${1}`" -le "${2}" ]
-}
-
-cleanup()
-{
-	is_empty "${TEMP}" || rm -rf "${TEMP}"
-}
-
-abort()
-{
-	echo "Fatal: $@"
-	exit 1
-}
-
-info()
-{
-	is_empty "${VERBOSE}" || echo "[*] $@"
-}
-
-prepare_workspace()
-{
-	umask 077
-
-	TEMP=`mktemp -d` || abort 'Failed to create working directory'
-	trap cleanup EXIT
-	cd "${TEMP}" || abort 'Failed to change working directory'
-}
-
 create_blob()
 {
 	ARGS="-m ${MEM_SIZE} -o ${1}"
 	INDEX=0
-	OLDIFS=${IFS}
 	IFS=:
 	for FILE in ${ARC_IMAGES}; do
 		if is_readable_file "${FILE}"; then
@@ -95,7 +24,7 @@ create_blob()
 			INDEX=$((${INDEX} + 1))
 		fi
 	done
-	IFS=${OLDIFS}
+	unset IFS
 	if is_readable_file "${INITRD}"; then
 		ARGS="${ARGS} -f ${INITRD} -t initrd"
 	fi
@@ -113,40 +42,28 @@ write_blob()
 {
 	case "${3}" in
 		A)
-			SECTOR=16384
+			write_lba "${1}" "${2}" 16384
 			;;
 		B)
-			SECTOR=81920
+			write_lba "${1}" "${2}" 81920
 			;;
 	esac
-
-	info "Flashing boot image"
-	dd if=${1} of=${2} bs=512 seek=${SECTOR} conv=fsync >${STDOUT} 2>&1
-}
-
-select_boot_source()
-{
-	info "Enabling boot source ${2}"
-	printf "opt${2}\0" | dd of=${1} bs=512 seek=64 conv=fsync >${STDOUT} 2>&1
 }
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-a <arc images>] [-c <cmdline>] [-d <device>] [-i <initrd>] [-m <mem-size>] [-o A|B] <vmlinux.bin>"
-	echo "       Default: -a ${ARC_IMAGES} -d ${DEVICE} -m ${MEM_SIZE} -o ${OPTION}"
+	echo "Usage: ${0} [-hqtv] [-a <arc images>] [-c <cmdline>] [-i <initrd>] [-m <mem-size>] [-o A|B] <vmlinux.bin>"
+	echo "       Default: -a ${ARC_IMAGES} -m ${MEM_SIZE} -o ${OPTION}"
 	exit ${1}
 }
 
-while getopts a:c:d:hi:m:o:qtv opt; do
+while getopts a:c:hi:m:o:qtv opt; do
 	case "${opt}" in
 		a)
 			ARC_IMAGES="${OPTARG}"
 			;;
 		c)
 			CMDLINE="${OPTARG}"
-			;;
-		d)
-			DEVICE="${OPTARG}"
 			;;
 		i)
 			INITRD="${OPTARG}"
@@ -157,36 +74,20 @@ while getopts a:c:d:hi:m:o:qtv opt; do
 		o)
 			OPTION="${OPTARG}"
 			;;
-		q)
-			VERBOSE=
-			;;
-		t)
-			set -x
-			;;
-		v)
-			STDOUT=/dev/stdout
-			;;
-		h|?)
-			if [ "${opt}" = "h" ]; then
-				usage 0
-			else
-				usage 1
-			fi
-			;;
 	esac
+	std_opt "${opt}"
 done
 
 shift $((${OPTIND} - 1))
 [ "$#" -eq 1 ] || usage 1
-VMLINUX="${1}"
+VMLINUX=`xrealpath ${1}`
 
-is_writeable_blockdev "${DEVICE}" || abort "Target block device '${DEVICE}' is not a writeable block device"
-OLDIFS=${IFS}
+is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
 IFS=:
 for FILE in ${ARC_IMAGES}; do
 	is_readable_file "${FILE}" || abort "Cannot access '${FILE}'"
 done
-IFS=${OLDIFS}
+unset IFS
 is_empty "${INITRD}" || is_readable_file "${INITRD}" || abort "Cannot access '${INITRD}'"
 ! is_empty "${VMLINUX}" || abort "No kernel image given"
 is_readable_file "${VMLINUX}" || abort "Cannot access '${VMLINUX}'"
@@ -199,8 +100,8 @@ case "${OPTION}" in
 		;;
 esac
 
-prepare_workspace
+create_workspace
 create_blob bootblob.bin || abort "Failed to create boot image"
 is_file_size_le bootblob.bin "${MAX_IMAGE_SIZE}" || abort "Boot image is too big"
-write_blob bootblob.bin "${DEVICE}" "${OPTION}" || abort "Failed to flash boot image"
-select_boot_source "${DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
+write_blob bootblob.bin "${MMC_DEVICE}" "${OPTION}" || abort "Failed to flash boot image"
+select_boot_source "${MMC_DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
diff --git a/flash-rescue b/flash-rescue
--- a/flash-rescue
+++ b/flash-rescue
@@ -3,114 +3,22 @@
 # Copyright (C) 2014 Dream Property GmbH
 #
 
-set -e
-
-DEVICE=/dev/mtdblock2
-VMLINUX=
-
-STDOUT=/dev/null
-TEMP=
-VERBOSE=1
-
-is_blockdev()
-{
-	[ -b "${1}" ]
-}
-
-is_file()
-{
-	[ -f "${1}" ]
-}
-
-is_readable()
-{
-	[ -r "${1}" ]
-}
-
-is_readable_file()
-{
-	is_file "${1}" && is_readable "${1}"
-}
-
-is_writeable()
-{
-	[ -w "${1}" ]
-}
-
-is_writeable_blockdev()
-{
-	is_blockdev "${1}" && is_writeable "${1}"
-}
-
-is_empty()
-{
-	[ -z "${1}" ]
-}
-
-is_file_size_le()
-{
-	[ "`stat -c '%s' ${1}`" -le "${2}" ]
-}
-
-is_file_size_le_blockdev()
-{
-	is_file_size_le "${1}" "$((`sfdisk -s ${2}` * 1024))"
-}
-
-abort()
-{
-	echo "Fatal: $@"
-	exit 1
-}
-
-info()
-{
-	is_empty "${VERBOSE}" || echo "[*] $@"
-}
-
-write_sync()
-{
-	info "Writing ${1} to ${2}"
-	dd if=${1} of=${2} bs=64K conv=fsync >${STDOUT} 2>&1
-}
+source librecovery
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-d <device>] <vmlinuz-rescue.bin>"
-	echo "       Default: -d ${DEVICE}"
+	echo "Usage: ${0} [-hqtv] <vmlinuz-rescue.bin>"
 	exit ${1}
 }
 
-while getopts d:hqtv opt; do
-	case "${opt}" in
-		d)
-			DEVICE="${OPTARG}"
-			;;
-		q)
-			VERBOSE=
-			;;
-		t)
-			set -x
-			;;
-		v)
-			STDOUT=/dev/stdout
-			;;
-		h|?)
-			if [ "${opt}" = "h" ]; then
-				usage 0
-			else
-				usage 1
-			fi
-			;;
-	esac
-done
-
+xgetopts $@
 shift $((${OPTIND} - 1))
 [ "$#" -eq 1 ] || usage 1
-VMLINUX="${1}"
+FILENAME=`xrealpath ${1}`
 
-is_writeable_blockdev "${DEVICE}" || abort "Target block device '${DEVICE}' is not a writeable block device"
-! is_empty "${VMLINUX}" || abort "No kernel image given"
-is_readable_file "${VMLINUX}" || abort "Cannot access '${VMLINUX}'"
-is_file_size_le_blockdev "${VMLINUX}" "${DEVICE}" || abort "Rescue image is too big"
-write_sync "${VMLINUX}" "${DEVICE}" || abort "Failed to write rescue image"
+is_writable_blockdev "${RESCUE_PARTITION}" || abort "Target block device '${RESCUE_PARTITION}' is not a writable block device"
+! is_empty "${FILENAME}" || abort "No kernel image given"
+is_readable_file "${FILENAME}" || abort "Cannot access '${FILENAME}'"
+is_file_size_le_blockdev "${FILENAME}" "${RESCUE_PARTITION}" || abort "Rescue image is too big"
+create_workspace
+write_blkdev "${FILENAME}" "${RESCUE_PARTITION}" || abort "Failed to write rescue image"
diff --git a/flash-tarball b/flash-tarball
--- a/flash-tarball
+++ b/flash-tarball
@@ -3,210 +3,38 @@
 # Copyright (C) 2014 Dream Property GmbH
 #
 
-set -e
-
-FILENAME=
-DEVICE=/dev/mmcblk0
-ROOT_PARTITION=${DEVICE}p1
-ROOT_MOUNTPOINT=/mnt
-ROOT_NAME=dreambox-rootfs
-DATA_PARTITION=${DEVICE}p2
-DATA_NAME=dreambox-data
-FILESYSTEM=ext4
-
-STDOUT=/dev/null
-TEMP=
-VERBOSE=1
-
-is_blockdev()
-{
-	[ -b "${1}" ]
-}
-
-is_file()
-{
-	[ -f "${1}" ]
-}
-
-is_readable()
-{
-	[ -r "${1}" ]
-}
-
-is_readable_file()
-{
-	is_file "${1}" && is_readable "${1}"
-}
-
-is_writeable()
-{
-	[ -w "${1}" ]
-}
-
-is_writeable_blockdev()
-{
-	is_blockdev "${1}" && is_writeable "${1}"
-}
-
-is_empty()
-{
-	[ -z "${1}" ]
-}
-
-is_initrd()
-{
-	is_file "/etc/initrd-release"
-}
-
-is_nfsroot()
-{
-	is_readable_file /proc/cmdline && grep -q -w root=/dev/nfs /proc/cmdline
-}
-
-is_mountpoint()
-{
-	mountpoint -q `realpath "${1}"`
-}
-
-cleanup()
-{
-	is_empty "${TEMP}" || rm -rf "${TEMP}"
-	unmount ${ROOT_MOUNTPOINT}
-}
-
-abort()
-{
-	echo "Fatal: $@"
-	exit 1
-}
-
-warn()
-{
-	echo "Warning: $@"
-}
-
-info()
-{
-	is_empty "${VERBOSE}" || echo "[*] $@"
-}
-
-prepare_workspace()
-{
-	umask 077
-
-	TEMP=`mktemp -d` || abort 'Failed to create working directory'
-	trap cleanup EXIT
-	cd "${TEMP}" || abort 'Failed to change working directory'
-}
-
-create_partition_table()
-{
-	info "Creating partition table"
-	parted --script --align=optimal "${1}" -- \
-		mklabel gpt \
-		mkpart primary ext2 72MiB 1GiB \
-		mkpart primary ext2 1GiB 100% >${STDOUT}
-}
-
-create_filesystem()
-{
-	info "Creating ${FILESYSTEM} filesystem '${1}' on ${2}"
-	mkfs.${FILESYSTEM} -L "${1}" "${2}" >${STDOUT}
-}
-
-extract()
-{
-	info "Extracting '${1}' to '${2}'"
-	tar -xf "${1}" -C "${2}" >${STDOUT}
-}
-
-run_postinsts()
-{
-	local virtfs="dev proc run sys tmp"
-	local mountpoint=$1
-	shift
-
-	if [ -d "${mountpoint}/var/lib/dpkg/info" ]; then
-		pkgtype="dpkg"
-	elif [ -d "${mountpoint}/var/lib/opkg/info" ]; then
-		pkgtype="opkg"
-	else
-		warn "Unknown package manager, can't run postinst scripts"
-		return
-	fi
-
-	for fs in ${virtfs}; do
-		mount -o bind /${fs} ${mountpoint}/${fs} || abort "Failed to mount ${mountpoint}/${fs}"
-	done
-	for package in $@; do
-		chroot ${mountpoint} /var/lib/${pkgtype}/info/${package}.postinst || abort "Failed to run ${package}.postinst"
-	done
-	for fs in ${virtfs}; do
-		unmount ${mountpoint}/${fs} || warn "Failed to unmount ${mountpoint}/${fs}"
-	done
-}
-
-unmount()
-{
-	if is_mountpoint "${1}"; then
-		info "Unmounting '${1}'"
-		umount "${1}" || mount -o remount,ro "${1}"
-	fi
-}
+source librecovery
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-d <device>] <dreambox-image.tar.[bz2|gz|xz]>"
-	echo "       Default: -d ${DEVICE}"
+	echo "Usage: ${0} [-hqtv] <dreambox-image.tar.xz>"
 	exit ${1}
 }
 
-while getopts d:hqtv opt; do
-	case "$opt" in
-		d)
-			DEVICE="${OPTARG}"
-			;;
-		q)
-			VERBOSE=
-			;;
-		t)
-			set -x
-			;;
-		v)
-			STDOUT=/dev/stdout
-			;;
-		h|?)
-			if [ "$opt" = "h" ]; then
-				usage 0
-			else
-				usage 1
-			fi
-			;;
-	esac
-done
-
+xgetopts $@
 shift $((${OPTIND} - 1))
 [ "$#" -eq 1 ] || usage 1
-FILENAME=${1}
+FILENAME=`xrealpath ${1}`
 
-is_initrd || is_nfsroot || abort "This script may only run in recovery mode!"
+assert_rescue_mode
 
-is_writeable_blockdev "${DEVICE}" || abort "Target block device '${DEVICE}' is not a writeable block device"
+is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
 ! is_empty "${FILENAME}" || abort "No tarball filename given"
 is_readable_file "${FILENAME}" || abort "Cannot access '${FILENAME}'"
-FILENAME=`realpath ${FILENAME}`
 
-prepare_workspace
+create_workspace
 
 if ! is_blockdev "${ROOT_PARTITION}" || ! is_blockdev "${DATA_PARTITION}"; then
-	create_partition_table "${DEVICE}" || abort "Failed to partition disk"
+	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+	unmount "${DATA_MOUNTPOINT}" || abort "Failed to unmount data filesystem"
+	create_partition_table "${MMC_DEVICE}" || abort "Failed to partition disk"
 	create_filesystem "${DATA_NAME}" "${DATA_PARTITION}" || warn "Failed to create ${FILESYSTEM} filesystem '${DATA_NAME}' on '${DATA_PARTITION}'"
 fi
 
+unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
 create_filesystem "${ROOT_NAME}" "${ROOT_PARTITION}" || abort "Failed to create ${FILESYSTEM} filesystem '${ROOT_NAME}' on '${ROOT_PARTITION}'"
-info "Mounting root filesystem"
-mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
-extract "${FILENAME}" "${ROOT_MOUNTPOINT}" || abort "Failed to extract root filesystem"
+safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
+extract_tarball "${FILENAME}" "${ROOT_MOUNTPOINT}" || abort "Failed to extract root filesystem"
 run_postinsts "${ROOT_MOUNTPOINT}" dreambox-secondstage kernel-image || abort "Failed to run postinst scripts"
 unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
-sync && info "Finished successfully. You may reboot now."
+info "Finished successfully. You may reboot now."
diff --git a/librecovery b/librecovery
--- a/librecovery
+++ b/librecovery
@@ -1,10 +1,7 @@
-#!/bin/sh
 #
 # Copyright (C) 2014 Dream Property GmbH
 #
 
-BASE_URI=http://dreamboxupdate.com/download/recovery/dm7080/release
-FILENAME=dreambox-image-dm7080.tar.xz
 MMC_DEVICE=/dev/mmcblk0
 ROOT_PARTITION=/dev/mmcblk0p1
 ROOT_MOUNTPOINT=/mnt
@@ -12,6 +9,7 @@ ROOT_NAME=dreambox-rootfs
 DATA_PARTITION=/dev/mmcblk0p2
 DATA_MOUNTPOINT=/data
 DATA_NAME=dreambox-data
+RESCUE_PARTITION=/dev/mtdblock2
 RECOVERY_CACHE=${DATA_MOUNTPOINT}/.recovery
 FILESYSTEM=ext4
 
@@ -43,6 +41,11 @@ is_readable()
 	[ -r "${1}" ]
 }
 
+is_readable_blockdev()
+{
+	is_blockdev "${1}" && is_readable "${1}"
+}
+
 is_readable_file()
 {
 	is_file "${1}" && is_readable "${1}"
@@ -58,9 +61,24 @@ is_writable_blockdev()
 	is_blockdev "${1}" && is_writable "${1}"
 }
 
+is_writable_directory()
+{
+	is_directory "${1}" && is_writable "${1}"
+}
+
 is_empty()
 {
 	[ -z "${1}" ]
+}
+
+is_file_size_le()
+{
+	[ "`stat -c '%s' ${1}`" -le "${2}" ]
+}
+
+is_file_size_le_blockdev()
+{
+	is_file_size_le "${1}" "$((`sfdisk -s ${2}` * 1024))"
 }
 
 is_initrd()
@@ -240,6 +258,17 @@ unmount_cache()
 	unmount "${DATA_MOUNTPOINT}"
 }
 
+run()
+{
+	local cmd="${1}"
+	shift
+
+	info "Running '${cmd}'"
+	is_empty "$@" || info "Options '$@'"
+	chmod 755 "${cmd}" || abort "Failed to set execute permissions"
+	${cmd} $@ || abort "Failed to execute '${cmd}'"
+}
+
 run_postinsts()
 {
 	local virtfs="dev proc run sys tmp"
@@ -269,6 +298,24 @@ run_postinsts()
 assert_rescue_mode()
 {
 	is_initrd || is_nfsroot || abort "This script may only run in rescue mode!"
+}
+
+write_blkdev()
+{
+	info "Writing ${1} to ${2}"
+	xdd if=${1} of=${2} bs=64K
+}
+
+write_lba()
+{
+	info "Writing ${1} to ${2} (LBA: ${3})"
+	xdd if="${1}" of="${2}" bs=512 seek="${3}"
+}
+
+select_boot_source()
+{
+	info "Enabling boot source ${2}"
+	printf "opt${2}\0" | xdd of=${1} bs=512 seek=64
 }
 
 usage()
@@ -355,51 +402,3 @@ xtrap()
 {
 	(trap '' HUP INT TERM; exec $@) >&3 2>&4
 }
-
-xgetopts $@
-
-assert_rescue_mode
-
-is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
-
-create_workspace
-export GNUPGHOME="${WORKSPACE}"
-
-(base64 -d > trustedkeys.gpg || abort 'Failed to write public key') << EOF
-mQENBFPo2oUBCAC6dzqe5azBCkxzj99xNfzwB4L6tHzz83zqD2KUQuuJMhO7Q2g9AHnSNQ0z1+Bz
-oX2gGX90FusBSLiCuZmNdnxlcl7KVfBe37EpYtQNGCZKlWeruCAUdJGKIyPJXDvkXCy3dj6z1ho8
-p1r3uazEbUbJyLvwjzcg0Ua1qxFjLoq/h15yDgd0NCkMStL6gwKdmReLRfE/tn0K53CVQzIeEFyn
-EW3N0tu2deiYkanHy/MM9IOIv3oQmoEWNaVsDf+gG7nUPj0QE66GOYlBugR5vNi3BorOctarQp/8
-Dh56muiqomwwewJubzsvjUjpiYXdO/3RN2gOej2+5hUCiYmvOahfABEBAAG0LkRyZWFtYm94IERN
-NzA4MCBSZWNvdmVyeSA8cmVjb3ZlcnlAZG03MDgwLmNvbT6JATgEEwECACIFAlPo2oUCGwMGCwkI
-BwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEBWob67Wz1bnUGYH/0zmTS7Gtvv97oHHnz3JSkLybDRj
-Jx/wH+vpzyCRl8rC7TlHs5GBfjoJ1Hjo4DsZqElTb8g+kg5WGzMBUUuwabRhZuf2CL7/IPKP+LWH
-t2ByZX3OgS1Q+HDLob5wlKllD9y/wwekuwS/8cgdnDH9URHCBqIt5gWQzLU1pvmQrKPXM1aMsLQj
-16vbktXNkREF/cNhWfQFQs2dOwmzNEDeuE32I6h7PYl1bFP0hCOmbkcTuibnC+tsWOJMKF1iZ8bq
-xDND9BYTwGtD2SVrddu3i4kBz6hka01ZnfSUZewpu+TrCgaD6oENfarPiC9VYfKEFi10RIPIxwRX
-s1tBOOQNKpywAgAD
-EOF
-
-mount_cache
-fetch_signed "${BASE_URI}" "${FILENAME}"
-
-if ! is_blockdev "${ROOT_PARTITION}" || ! is_blockdev "${DATA_PARTITION}"; then
-	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
-	unmount "${DATA_MOUNTPOINT}" || abort "Failed to unmount data filesystem"
-	create_partition_table "${MMC_DEVICE}" || abort "Failed to partition disk"
-	create_filesystem "${DATA_NAME}" "${DATA_PARTITION}" || warn "Failed to create ${FILESYSTEM} filesystem '${DATA_NAME}' on '${DATA_PARTITION}'"
-	mount_cache
-fi
-
-unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
-create_filesystem "${ROOT_NAME}" "${ROOT_PARTITION}" || abort "Failed to create ${FILESYSTEM} filesystem '${ROOT_NAME}' on '${ROOT_PARTITION}'"
-safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
-extract_tarball "${FILENAME}" "${ROOT_MOUNTPOINT}" || abort "Failed to extract root filesystem"
-run_postinsts "${ROOT_MOUNTPOINT}" dreambox-secondstage kernel-image || abort "Failed to run postinst scripts"
-unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
-
-update_cache "${FILENAME}"
-unmount_cache
-
-info "Initiating reboot"
-sync && reboot || warn 'Failed to initiate reboot'
diff --git a/select-boot-source b/select-boot-source
--- a/select-boot-source
+++ b/select-boot-source
@@ -3,88 +3,20 @@
 # Copyright (C) 2014 Dream Property GmbH
 #
 
-set -e
-
-DEVICE=/dev/mmcblk0
-OPTION=
-
-STDOUT=/dev/null
-TEMP=
-VERBOSE=1
-
-is_blockdev()
-{
-	[ -b "${1}" ]
-}
-
-is_writeable()
-{
-	[ -w "${1}" ]
-}
-
-is_writeable_blockdev()
-{
-	is_blockdev "${1}" && is_writeable "${1}"
-}
-
-is_empty()
-{
-	[ -z "${1}" ]
-}
-
-abort()
-{
-	echo "Fatal: $@"
-	exit 1
-}
-
-info()
-{
-	is_empty "${VERBOSE}" || echo "[*] $@"
-}
-
-select_boot_source()
-{
-	info "Enabling boot source ${2}"
-	printf "opt${2}\0" | dd of=${1} bs=512 seek=64 conv=fsync >${STDOUT} 2>&1
-}
+source librecovery
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-d <device>] [A|B|C]"
-	echo "       Default: -d ${DEVICE}"
+	echo "Usage: ${0} [-hqtv] <A|B|C>"
 	exit ${1}
 }
 
-while getopts d:hqtv opt; do
-	case "${opt}" in
-		d)
-			DEVICE="${OPTARG}"
-			;;
-		q)
-			VERBOSE=
-			;;
-		t)
-			set -x
-			;;
-		v)
-			STDOUT=/dev/stdout
-			;;
-		h|?)
-			if [ "$opt" = "h" ]; then
-				usage 0
-			else
-				usage 1
-			fi
-			;;
-	esac
-done
-
+xgetopts $@
 shift $((${OPTIND} - 1))
 [ "$#" -eq 1 ] || usage 1
 OPTION=${1}
 
-is_writeable_blockdev "${DEVICE}" || abort "Target block device '${DEVICE}' is not a writeable block device"
+is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
 ! is_empty "${OPTION}" || abort "No option given"
 
 case "${OPTION}" in
@@ -95,4 +27,4 @@ case "${OPTION}" in
 		;;
 esac
 
-select_boot_source "${DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
+select_boot_source "${MMC_DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
