Revert "flash-kernel add ofgwrite multiboot support"
This reverts commit 755c6995cdc8da58a5ad2ff72b77b643cb101d76.

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -10,8 +10,7 @@ case "${MACHINE}" in
 		DEVICETREE=/boot/dream${MACHINE}.dtb
 		CMDLINE=
 		INITRD=
-		OFGROOT=
-		OPTSTRING="r:c:d:hi:qtv"
+		OPTSTRING="c:d:hi:qtv"
 		;;
 esac
 
@@ -57,7 +56,7 @@ create_bootimg()
 	if is_empty "${CMDLINE}"; then
 		mkbootimg ${ARGS} >&3 2>&4
 	else
-		if is_gpt && [ -z "$OFGROOT" ]; then
+		if is_gpt; then
 			CMDLINE=$(echo ${CMDLINE} | sed -e "s/mmcblk0p7/${CMDLINE_ROOTFS}/g")
 		fi
 		info "Kernel command-line: ${CMDLINE}"
@@ -79,7 +78,7 @@ write_blob()
 
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-c <cmdline>] [-d <devicetree>] [-i <initrd>] [-r <OFGROOT>] <vmlinux.bin>"
+	echo "Usage: ${0} [-hqtv] [-c <cmdline>] [-d <devicetree>] [-i <initrd>] <vmlinux.bin>"
 	echo "       Default: -d ${DEVICETREE}"
 	exit ${1}
 }
@@ -104,9 +103,6 @@ while getopts ${OPTSTRING} opt; do
 		o)
 			OPTION="${OPTARG}"
 			;;
-		r)
-			OFGROOT="${OPTARG}"
-			;;
 	esac
 	std_opt "${opt}"
 done
@@ -126,7 +122,7 @@ case "${MACHINE}" in
 	one|two|seven)
 		create_workspace
 		if is_gpt; then
-			create_bootimg "${OFGROOT}/boot/kernel.img" || abort "Failed to create boot image"
+			create_bootimg "/boot/kernel.img" || abort "Failed to create boot image"
 		else
 			create_bootimg bootblob.bin || abort "Failed to create boot image"
 			is_file_size_le bootblob.bin "${KERNEL_SIZE}" || abort "Boot image is too big"
