WIP: port to dm520 (nand, no data partition)
still missing: reboot to rescue, writespi for new soc, possibly flash-ssbl

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -1,107 +1,26 @@
 #!/bin/sh
 #
-# Copyright (C) 2014 Dream Property GmbH
+# Copyright (C) 2016 Dream Property GmbH
 #
 
 source librecovery
 
-MEM_SIZE=0x10000000
-ARC_IMAGES=/usr/share/fastboot/lcd_anim.bin
-MAX_IMAGE_SIZE=$((32 * 1024 * 1024))
-OPTION=A
-VMLINUX=
-CMDLINE=
-INITRD=
-
-create_blob()
-{
-	ARGS="-m ${MEM_SIZE} -o ${1}"
-	INDEX=0
-	IFS=:
-	for FILE in ${ARC_IMAGES}; do
-		if is_readable_file "${FILE}"; then
-			ARGS="${ARGS} -f ${FILE} -t arc -i ${INDEX}"
-			INDEX=$((${INDEX} + 1))
-		fi
-	done
-	unset IFS
-	if is_readable_file "${INITRD}"; then
-		ARGS="${ARGS} -f ${INITRD} -t initrd"
-	fi
-	if ! is_empty "${CMDLINE}"; then
-		echo -n "${CMDLINE}" > cmdline.txt
-		ARGS="${ARGS} -f cmdline.txt -t cmdline"
-	fi
-	ARGS="${ARGS} -f ${VMLINUX} -t kernel -d 0x1000"
-
-	info "Creating boot image"
-	mkbootblob ${ARGS} >&3 2>&4
-}
-
-write_blob()
-{
-	case "${3}" in
-		A)
-			write_lba "${1}" "${2}" 16384
-			;;
-		B)
-			write_lba "${1}" "${2}" 81920
-			;;
-	esac
-}
-
 usage()
 {
-	echo "Usage: ${0} [-hqtv] [-a <arc images>] [-c <cmdline>] [-i <initrd>] [-m <mem-size>] [-o A|B] <vmlinux.bin>"
-	echo "       Default: -a ${ARC_IMAGES} -m ${MEM_SIZE} -o ${OPTION}"
+	echo "Usage: ${0} [-hqtv] <vmlinux.gz>"
 	exit ${1}
 }
 
-while getopts a:c:hi:m:o:qtv opt; do
-	case "${opt}" in
-		a)
-			ARC_IMAGES="${OPTARG}"
-			;;
-		c)
-			CMDLINE="${OPTARG}"
-			;;
-		i)
-			INITRD="${OPTARG}"
-			;;
-		m)
-			MEM_SIZE="${OPTARG}"
-			;;
-		o)
-			OPTION="${OPTARG}"
-			;;
-	esac
-	std_opt "${opt}"
-done
-
+xgetopts $@
 shift $((${OPTIND} - 1))
 [ "$#" -eq 1 ] || usage 1
 VMLINUX=`xrealpath ${1}`
 
-is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
-IFS=:
-for FILE in ${ARC_IMAGES}; do
-	is_readable_file "${FILE}" || abort "Cannot access '${FILE}'"
-done
-unset IFS
-is_empty "${INITRD}" || is_readable_file "${INITRD}" || abort "Cannot access '${INITRD}'"
+MTD_DEVICE=/dev/mtd2
+
+is_writable_chardev "${MTD_DEVICE}" || abort "Target device '${MTD_DEVICE}' is not a writable character device"
 ! is_empty "${VMLINUX}" || abort "No kernel image given"
 is_readable_file "${VMLINUX}" || abort "Cannot access '${VMLINUX}'"
 
-case "${OPTION}" in
-	A|B)
-		;;
-	*)
-		abort "Invalid boot option: ${OPTION}"
-		;;
-esac
-
-create_workspace
-create_blob bootblob.bin || abort "Failed to create boot image"
-is_file_size_le bootblob.bin "${MAX_IMAGE_SIZE}" || abort "Boot image is too big"
-write_blob bootblob.bin "${MMC_DEVICE}" "${OPTION}" || abort "Failed to flash boot image"
-select_boot_source "${MMC_DEVICE}" "${OPTION}" || abort "Failed to enable boot source"
+erase "${MTD_DEVICE}" || abort "Failed to erase ${MTD_DEVICE}"
+write_nand "${MTD_DEVICE}" "${VMLINUX}" || abort "Failed to flash kernel image"
diff --git a/librecovery b/librecovery
--- a/librecovery
+++ b/librecovery
@@ -1,17 +1,15 @@
 #
-# Copyright (C) 2014 Dream Property GmbH
+# Copyright (C) 2016 Dream Property GmbH
 #
 
-MMC_DEVICE=/dev/mmcblk0
-ROOT_PARTITION=/dev/mmcblk0p1
+MTD_DEVICE=/dev/mtd0
+UBI_ID=0
+UBI_DEVICE=/dev/ubi${UBI_ID}
+UBI_VOL_ID=0
+ROOT_PARTITION=${UBI_DEVICE}_${UBI_VOL_ID}
 ROOT_MOUNTPOINT=/mnt
 ROOT_NAME=dreambox-rootfs
-DATA_PARTITION=/dev/mmcblk0p2
-DATA_MOUNTPOINT=/data
-DATA_NAME=dreambox-data
-RESCUE_PARTITION=/dev/mtdblock2
-RECOVERY_CACHE=${DATA_MOUNTPOINT}/.recovery
-FILESYSTEM=ext4
+FILESYSTEM=ubifs
 
 MOUNTPOINTS=
 WORKSPACE=
@@ -40,6 +38,11 @@ is_beneath_directory()
 is_blockdev()
 {
 	[ -b "${1}" ]
+}
+
+is_chardev()
+{
+	[ -c "${1}" ]
 }
 
 is_directory()
@@ -75,6 +78,11 @@ is_writable()
 is_writable_blockdev()
 {
 	is_blockdev "${1}" && is_writable "${1}"
+}
+
+is_writable_chardev()
+{
+	is_chardev "${1}" && is_writable "${1}"
 }
 
 is_writable_directory()
@@ -154,17 +162,44 @@ create_directory()
 
 create_filesystem()
 {
-	info "Creating ${FILESYSTEM} filesystem '${1}' on ${2}"
-	xtrap mkfs.${FILESYSTEM} -L "${1}" "${2}" >&3 2>&4
+	info "Creating ${FILESYSTEM} filesystem on ${1}"
+	xtrap mkfs.${FILESYSTEM} "${1}"
 }
 
-create_partition_table()
+erase()
 {
-	info "Creating partition table"
-	xtrap parted --script --align=optimal "${1}" -- \
-		mklabel gpt \
-		mkpart primary ext2 72MiB 1GiB \
-		mkpart primary ext2 1GiB 100% >&3 2>&4
+	info "Erasing flash memory on ${1}"
+	xtrap flash_erase "${1}" 0 0
+}
+
+write_nand()
+{
+	info "Writing to NAND memory on ${1}"
+	xtrap nandwrite -p -m "${1}" "${2}"
+}
+
+format_ubi_device()
+{
+	info "Formatting ${1} for UBI"
+	xtrap ubiformat -y "${1}"
+}
+
+attach_ubi_device()
+{
+	info "Attaching ${1} to UBI"
+	xtrap ubiattach -d "${UBI_ID}" -p "${1}"
+}
+
+remove_ubi_volume()
+{
+	info "Removing volume ${UBI_VOL_ID} from ${UBI_DEVICE}"
+	xtrap ubirmvol "${UBI_DEVICE}" -n "${UBI_VOL_ID}"
+}
+
+create_ubi_volume()
+{
+	info "Creating volume ${UBI_VOL_ID} on ${UBI_DEVICE} (${ROOT_NAME})"
+	xtrap ubimkvol "${UBI_DEVICE}" -n "${UBI_VOL_ID}" -N "${ROOT_NAME}" -m
 }
 
 create_tarball()
@@ -235,28 +270,11 @@ verify()
 	gpgv -q --ignore-time-conflict "${1}.sig" "${1}" >&3 2>&4
 }
 
-files_equal()
-{
-	cmp -s "${1}" "${2}"
-}
-
 fetch_signed()
 {
-	fetch "${1}" "${2}.sig" || true
-
-	if is_file "${RECOVERY_CACHE}/${2}" && is_file "${RECOVERY_CACHE}/${2}.sig"; then
-		if ! is_file "${2}.sig" || files_equal "${2}.sig" "${RECOVERY_CACHE}/${2}.sig"; then
-			info "Copying '${2}' from local storage"
-			xcp "${RECOVERY_CACHE}/${2}.sig" "${2}.sig"
-			xcp "${RECOVERY_CACHE}/${2}" "${2}"
-		fi
-	fi
-
-	is_file "${2}.sig" || abort "Failed to obtain signature '${2}.sig'"
-	is_file "${2}" && verify "${2}" || {
-		fetch "${1}" "${2}" || abort "Failed to download '${2}'"
-		verify "${2}" || abort 'Failed to verify signature'
-	}
+	fetch "${1}" "${2}.sig" || abort "Failed to obtain signature '${2}.sig'"
+	fetch "${1}" "${2}" || abort "Failed to download '${2}'"
+	verify "${2}" || abort 'Failed to verify signature'
 }
 
 safe_mount()
@@ -281,41 +299,6 @@ unmount()
 		info "Unmounting '${1}'"
 		umount "${1}" || mount -o remount,ro "${1}"
 	fi
-}
-
-mount_cache()
-{
-	if is_blockdev "${DATA_PARTITION}"; then
-		safe_mount "${DATA_PARTITION}" "${DATA_MOUNTPOINT}" -o ro || warn "Failed to mount data filesystem"
-	fi
-}
-
-cache_changed()
-{
-	is_mountpoint "${DATA_MOUNTPOINT}" && ! cmp -s "${RECOVERY_CACHE}/${1}.sig" "${1}.sig"
-}
-
-remount_cache_rw()
-{
-	is_mountpoint "${DATA_MOUNTPOINT}" && info "Remounting '${DATA_MOUNTPOINT}' (rw)" && \
-		mount -o remount,rw "${DATA_MOUNTPOINT}" && is_writable "${DATA_MOUNTPOINT}"
-}
-
-update_cache()
-{
-	if cache_changed "${1}" && remount_cache_rw; then
-		create_directory "${RECOVERY_CACHE}"
-		if is_directory "${RECOVERY_CACHE}"; then
-			info "Updating recovery cache"
-			xcp "${1}" "${RECOVERY_CACHE}/${1}" || true
-			xcp "${1}.sig" "${RECOVERY_CACHE}/${1}.sig" || true
-		fi
-	fi
-}
-
-unmount_cache()
-{
-	unmount "${DATA_MOUNTPOINT}"
 }
 
 run()
diff --git a/recovery b/recovery
--- a/recovery
+++ b/recovery
@@ -1,19 +1,18 @@
 #!/bin/sh
 #
-# Copyright (C) 2014 Dream Property GmbH
+# Copyright (C) 2016 Dream Property GmbH
 #
 
-BASE_URI=http://dreamboxupdate.com/download/recovery/dm7080/release
-FILENAME=dreambox-image-dm7080.tar.xz
-MMC_DEVICE=/dev/mmcblk0
-ROOT_PARTITION=/dev/mmcblk0p1
+BASE_URI=http://dreamboxupdate.com/download/recovery/dm520/release
+FILENAME=dreambox-image-dm520.tar.xz
+MTD_DEVICE=/dev/mtd0
+UBI_ID=0
+UBI_DEVICE=/dev/ubi${UBI_ID}
+UBI_VOL_ID=0
+ROOT_PARTITION=${UBI_DEVICE}_${UBI_VOL_ID}
 ROOT_MOUNTPOINT=/mnt
 ROOT_NAME=dreambox-rootfs
-DATA_PARTITION=/dev/mmcblk0p2
-DATA_MOUNTPOINT=/data
-DATA_NAME=dreambox-data
-RECOVERY_CACHE=${DATA_MOUNTPOINT}/.recovery
-FILESYSTEM=ext4
+FILESYSTEM=ubifs
 
 MOUNTPOINTS=
 WORKSPACE=
@@ -22,10 +21,11 @@ set -e
 
 exec 3>/dev/null
 exec 4>&2
+exec 5>&1
 
-is_blockdev()
+is_chardev()
 {
-	[ -b "${1}" ]
+	[ -c "${1}" ]
 }
 
 is_directory()
@@ -53,9 +53,9 @@ is_writable()
 	[ -w "${1}" ]
 }
 
-is_writable_blockdev()
+is_writable_chardev()
 {
-	is_blockdev "${1}" && is_writable "${1}"
+	is_chardev "${1}" && is_writable "${1}"
 }
 
 is_empty()
@@ -102,12 +102,12 @@ abort()
 
 warn()
 {
-	echo "Warning: $@"
+	echo "Warning: $@" >&5
 }
 
 info()
 {
-	echo "[*] $@" >&3
+	echo "[*] $@" >&5
 }
 
 create_directory()
@@ -120,17 +120,38 @@ create_directory()
 
 create_filesystem()
 {
-	info "Creating ${FILESYSTEM} filesystem '${1}' on ${2}"
-	xtrap mkfs.${FILESYSTEM} -L "${1}" "${2}" >&3 2>&4
+	info "Creating ${FILESYSTEM} filesystem on ${1}"
+	xtrap mkfs.${FILESYSTEM} "${1}"
 }
 
-create_partition_table()
+erase()
 {
-	info "Creating partition table"
-	xtrap parted --script --align=optimal "${1}" -- \
-		mklabel gpt \
-		mkpart primary ext2 72MiB 1GiB \
-		mkpart primary ext2 1GiB 100% >&3 2>&4
+	info "Erasing flash memory on ${1}"
+	xtrap flash_erase "${1}" 0 0
+}
+
+format_ubi_device()
+{
+	info "Formatting ${1} for UBI"
+	xtrap ubiformat -y "${1}"
+}
+
+attach_ubi_device()
+{
+	info "Attaching ${1} to UBI"
+	xtrap ubiattach -d "${UBI_ID}" -p "${1}"
+}
+
+remove_ubi_volume()
+{
+	info "Removing volume ${UBI_VOL_ID} from ${UBI_DEVICE}"
+	xtrap ubirmvol "${UBI_DEVICE}" -n "${UBI_VOL_ID}"
+}
+
+create_ubi_volume()
+{
+	info "Creating volume ${UBI_VOL_ID} on ${UBI_DEVICE} (${ROOT_NAME})"
+	xtrap ubimkvol "${UBI_DEVICE}" -n "${UBI_VOL_ID}" -N "${ROOT_NAME}" -m
 }
 
 create_workspace()
@@ -160,28 +181,11 @@ verify()
 	gpgv -q --ignore-time-conflict "${1}.sig" "${1}" >&3 2>&4
 }
 
-files_equal()
-{
-	cmp -s "${1}" "${2}"
-}
-
 fetch_signed()
 {
-	fetch "${1}" "${2}.sig" || true
-
-	if is_file "${RECOVERY_CACHE}/${2}" && is_file "${RECOVERY_CACHE}/${2}.sig"; then
-		if ! is_file "${2}.sig" || files_equal "${2}.sig" "${RECOVERY_CACHE}/${2}.sig"; then
-			info "Copying '${2}' from local storage"
-			xcp "${RECOVERY_CACHE}/${2}.sig" "${2}.sig"
-			xcp "${RECOVERY_CACHE}/${2}" "${2}"
-		fi
-	fi
-
-	is_file "${2}.sig" || abort "Failed to obtain signature '${2}.sig'"
-	is_file "${2}" && verify "${2}" || {
-		fetch "${1}" "${2}" || abort "Failed to download '${2}'"
-		verify "${2}" || abort 'Failed to verify signature'
-	}
+	fetch "${1}" "${2}.sig" || abort "Failed to obtain signature '${2}.sig'"
+	fetch "${1}" "${2}" || abort "Failed to download '${2}'"
+	verify "${2}" || abort 'Failed to verify signature'
 }
 
 safe_mount()
@@ -206,41 +210,6 @@ unmount()
 		info "Unmounting '${1}'"
 		umount "${1}" || mount -o remount,ro "${1}"
 	fi
-}
-
-mount_cache()
-{
-	if is_blockdev "${DATA_PARTITION}"; then
-		safe_mount "${DATA_PARTITION}" "${DATA_MOUNTPOINT}" -o ro || warn "Failed to mount data filesystem"
-	fi
-}
-
-cache_changed()
-{
-	is_mountpoint "${DATA_MOUNTPOINT}" && ! cmp -s "${RECOVERY_CACHE}/${1}.sig" "${1}.sig"
-}
-
-remount_cache_rw()
-{
-	is_mountpoint "${DATA_MOUNTPOINT}" && info "Remounting '${DATA_MOUNTPOINT}' (rw)" && \
-		mount -o remount,rw "${DATA_MOUNTPOINT}" && is_writable "${DATA_MOUNTPOINT}"
-}
-
-update_cache()
-{
-	if cache_changed "${1}" && remount_cache_rw; then
-		create_directory "${RECOVERY_CACHE}"
-		if is_directory "${RECOVERY_CACHE}"; then
-			info "Updating recovery cache"
-			xcp "${1}" "${RECOVERY_CACHE}/${1}" || true
-			xcp "${1}.sig" "${RECOVERY_CACHE}/${1}.sig" || true
-		fi
-	fi
-}
-
-unmount_cache()
-{
-	unmount "${DATA_MOUNTPOINT}"
 }
 
 run_postinsts()
@@ -286,6 +255,7 @@ std_opt()
 		q)
 			exec 3>/dev/null
 			exec 4>/dev/null
+			exec 5>/dev/null
 			;;
 		t)
 			set -x
@@ -293,6 +263,7 @@ std_opt()
 		v)
 			exec 3>&1
 			exec 4>&2
+			exec 5>&1
 			;;
 		h|'?')
 			if [ "${1}" = "h" ]; then
@@ -363,46 +334,45 @@ xgetopts $@
 
 assert_rescue_mode
 
-is_writable_blockdev "${MMC_DEVICE}" || abort "Target block device '${MMC_DEVICE}' is not a writable block device"
+is_writable_chardev "${MTD_DEVICE}" || abort "Target device '${MTD_DEVICE}' is not a writable character device"
 
 create_workspace
 export GNUPGHOME="${WORKSPACE}"
 
 (base64 -d > trustedkeys.gpg || abort 'Failed to write public key') << EOF
-mQENBFPo2oUBCAC6dzqe5azBCkxzj99xNfzwB4L6tHzz83zqD2KUQuuJMhO7Q2g9AHnSNQ0z1+Bz
-oX2gGX90FusBSLiCuZmNdnxlcl7KVfBe37EpYtQNGCZKlWeruCAUdJGKIyPJXDvkXCy3dj6z1ho8
-p1r3uazEbUbJyLvwjzcg0Ua1qxFjLoq/h15yDgd0NCkMStL6gwKdmReLRfE/tn0K53CVQzIeEFyn
-EW3N0tu2deiYkanHy/MM9IOIv3oQmoEWNaVsDf+gG7nUPj0QE66GOYlBugR5vNi3BorOctarQp/8
-Dh56muiqomwwewJubzsvjUjpiYXdO/3RN2gOej2+5hUCiYmvOahfABEBAAG0LkRyZWFtYm94IERN
-NzA4MCBSZWNvdmVyeSA8cmVjb3ZlcnlAZG03MDgwLmNvbT6JATgEEwECACIFAlPo2oUCGwMGCwkI
-BwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEBWob67Wz1bnUGYH/0zmTS7Gtvv97oHHnz3JSkLybDRj
-Jx/wH+vpzyCRl8rC7TlHs5GBfjoJ1Hjo4DsZqElTb8g+kg5WGzMBUUuwabRhZuf2CL7/IPKP+LWH
-t2ByZX3OgS1Q+HDLob5wlKllD9y/wwekuwS/8cgdnDH9URHCBqIt5gWQzLU1pvmQrKPXM1aMsLQj
-16vbktXNkREF/cNhWfQFQs2dOwmzNEDeuE32I6h7PYl1bFP0hCOmbkcTuibnC+tsWOJMKF1iZ8bq
-xDND9BYTwGtD2SVrddu3i4kBz6hka01ZnfSUZewpu+TrCgaD6oENfarPiC9VYfKEFi10RIPIxwRX
-s1tBOOQNKpywAgAD
+mQENBFcLsf0BCADDo4SxnQwl16cWSYnTwwp+E6ZvdhY3x9yw7b//MUDELtKkEp7wZ+AtHDYd+jzJ
+Syc+n1m4MkArNUzCdseFJJAYEsNEjZ6ZkoMSQ/GZsIKi2IYT0LXN+9c2ZLLZstNZ2201KwqjFkpE
+GXSn7VeLAvm82UgMaECY+4vJ5K3XtsLX6onCfidKy4qI8si4CTLylkDegGQ035FlkzqMKA8flafd
+RGiEWO/2o2ZdYgdjOYQq6W2MaI6zgDzg1V2HMXSweIxnhn8W4iZF80nLTPihoe+p3FRKX0d2G4B0
+wM49BTgfOgdcu3d3xZBRndOUXq0biga814jYLm3o+DqCmfmt3fsVABEBAAG0NERyZWFtYm94IERN
+NTIwIFJlY292ZXJ5IDxkbTUyMEByZWNvdmVyeS5kcmVhbWJveC5kZT6JATgEEwECACIFAlcLsf0C
+GwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJENzmv7ygdoPTTw0IAIN+WQMjAQGbSEo6DP41
+U8g3u3gRVxBWpAPeE8wsq3wMjmDK4kcCohnWzJSqb7O4XFDUO0fsg0InojpYCIvfhSK+7eohwIaJ
+ilkdM37nUY7TioFY3pOx63ZzDAJ5SsirU26CIxB+hHWueaS/XsGinodzxl6H9/l8I33U/2DN1oUe
+y9JcHVNxdBRtSNZMYyZXlA+4LrkDDN6/c6kpIG2uZEYOH0WlP+Mqu9G81yYYKiK9MTlsYHcCoSlV
+XR8VVsVBxKkfSsoWLMkhE7aEFqq+FeVjcrRyc7R+QGhdzwq9gK50iXpr+YxfHJNn2FML185NGwyp
+Gnvzh5YpHKnihOS+J7c=
 EOF
 
-mount_cache
 fetch_signed "${BASE_URI}" "${FILENAME}"
 
-if ! is_blockdev "${ROOT_PARTITION}" || ! is_blockdev "${DATA_PARTITION}"; then
-	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
-	unmount "${DATA_MOUNTPOINT}" || abort "Failed to unmount data filesystem"
-	create_partition_table "${MMC_DEVICE}" || abort "Failed to partition disk"
-	create_filesystem "${DATA_NAME}" "${DATA_PARTITION}" || warn "Failed to create ${FILESYSTEM} filesystem '${DATA_NAME}' on '${DATA_PARTITION}'"
-	mount_cache
+if ! is_chardev "${UBI_DEVICE}" && ! attach_ubi_device "${MTD_DEVICE}"; then
+	erase "${MTD_DEVICE}" || abort "Failed to erase ${MTD_DEVICE}"
+	format_ubi_device "${MTD_DEVICE}" || abort "Failed to format ${MTD_DEVICE}"
+	attach_ubi_device "${MTD_DEVICE}" || abort "Failed to attach ${MTD_DEVICE} to UBI"
 fi
 
-unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
-create_filesystem "${ROOT_NAME}" "${ROOT_PARTITION}" || abort "Failed to create ${FILESYSTEM} filesystem '${ROOT_NAME}' on '${ROOT_PARTITION}'"
+if is_chardev "${ROOT_PARTITION}"; then
+	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
+	remove_ubi_volume || abort "Failed to remove UBI volume"
+fi
+
+create_ubi_volume || abort "Failed to create UBI volume"
+create_filesystem "${ROOT_PARTITION}" || abort "Failed to create ${FILESYSTEM} filesystem on '${ROOT_PARTITION}'"
 safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
 extract_tarball "${FILENAME}" "${ROOT_MOUNTPOINT}" || abort "Failed to extract root filesystem"
 run_postinsts "${ROOT_MOUNTPOINT}" dreambox-secondstage kernel-image || abort "Failed to run postinst scripts"
 unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
-
-update_cache "${FILENAME}"
-unmount_cache
 
 info "Initiating reboot"
 sync && reboot || warn 'Failed to initiate reboot'
