librecovery: generalize

diff --git a/librecovery b/librecovery
--- a/librecovery
+++ b/librecovery
@@ -2,16 +2,11 @@
 # Copyright (C) 2016 Dream Property GmbH
 #
 
-MMC_DEVICE=/dev/mmcblk0
-KERNEL_PARTITION=/dev/mmcblk0p1
-ROOT_PARTITION=/dev/mmcblk0p2
 ROOT_MOUNTPOINT=/mnt
 ROOT_NAME=dreambox-rootfs
-DATA_PARTITION=/dev/mmcblk0p3
 DATA_MOUNTPOINT=/data
 DATA_NAME=dreambox-data
 RECOVERY_CACHE=${DATA_MOUNTPOINT}/.recovery
-FILESYSTEM=ext4
 
 MOUNTPOINTS=
 WORKSPACE=
@@ -21,6 +16,176 @@ set -e
 exec 3>/dev/null
 exec 4>&2
 exec 5>&1
+
+librecovery_init()
+{
+	read MID </proc/stb/info/mid
+
+	eval `tpm-ca 2>/dev/null | grep '^CA_[A-Z]\+=[A-Z0-9:_-]\+$'`
+	if [ -z "$CA_MID" ]; then
+		warn "Could not read CA!"
+	elif [ "$MID" != "$CA_MID" ]; then
+		warn "Detected incompatible drivers!"
+		MID="$CA_MID"
+	fi
+
+	case "$MID" in
+		19)
+			MACHINE="dm7080"
+			RECOVERY_KEY="
+				mQENBFPo2oUBCAC6dzqe5azBCkxzj99xNfzwB4L6tHzz83zqD2KUQuuJMhO7Q2g9AHnSNQ0z1+Bz
+				oX2gGX90FusBSLiCuZmNdnxlcl7KVfBe37EpYtQNGCZKlWeruCAUdJGKIyPJXDvkXCy3dj6z1ho8
+				p1r3uazEbUbJyLvwjzcg0Ua1qxFjLoq/h15yDgd0NCkMStL6gwKdmReLRfE/tn0K53CVQzIeEFyn
+				EW3N0tu2deiYkanHy/MM9IOIv3oQmoEWNaVsDf+gG7nUPj0QE66GOYlBugR5vNi3BorOctarQp/8
+				Dh56muiqomwwewJubzsvjUjpiYXdO/3RN2gOej2+5hUCiYmvOahfABEBAAG0LkRyZWFtYm94IERN
+				NzA4MCBSZWNvdmVyeSA8cmVjb3ZlcnlAZG03MDgwLmNvbT6JATgEEwECACIFAlPo2oUCGwMGCwkI
+				BwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEBWob67Wz1bnUGYH/0zmTS7Gtvv97oHHnz3JSkLybDRj
+				Jx/wH+vpzyCRl8rC7TlHs5GBfjoJ1Hjo4DsZqElTb8g+kg5WGzMBUUuwabRhZuf2CL7/IPKP+LWH
+				t2ByZX3OgS1Q+HDLob5wlKllD9y/wwekuwS/8cgdnDH9URHCBqIt5gWQzLU1pvmQrKPXM1aMsLQj
+				16vbktXNkREF/cNhWfQFQs2dOwmzNEDeuE32I6h7PYl1bFP0hCOmbkcTuibnC+tsWOJMKF1iZ8bq
+				xDND9BYTwGtD2SVrddu3i4kBz6hka01ZnfSUZewpu+TrCgaD6oENfarPiC9VYfKEFi10RIPIxwRX
+				s1tBOOQNKpywAgAD
+			"
+			;;
+		20)
+			MACHINE="dm820"
+			RECOVERY_KEY="
+				mQENBFQ5xy0BCADyK6WY3xcKICfVFSbQQ+GXYK9k54bXJ4d2jNaSfk4yAU/YNo2d2ZNTvsN2fQTV
+				2hwQb1yamJ9MDfqS46qio2rxTBpCNjWwn08ANrn5O52VVy/72xceuUl1XW+Hf0ANF2jtgLTzNpIT
+				7uQBXxww7/3WSeoK6EP2xb7cbn5PHxtfv/b71wdq3nUYZWOzHOA4mfaRMZ61n37BkADiA8QJKKNN
+				6xm4gDMTrAZF1QRC5xtVZ0xHgPRxjD2So3+s5Jf+BL+W5OfOeI8/S3VdHDmvLi30D6D3jAGQKYtu
+				gnf6UaBBczoN5otwmeIOdHpxK4hSk8AY0C+umJdaDt6szELgGTq/ABEBAAG0LERyZWFtYm94IERN
+				ODIwIFJlY292ZXJ5IDxyZWNvdmVyeUBkbTgyMC5jb20+iQE4BBMBAgAiBQJUOcctAhsDBgsJCAcD
+				AgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAmJQHXeeLAz2QdCACCxIcajDZ/Zl9V+jAubsCqPlh8Ep+v
+				ECizcjF7YiG9br3HGZCD8SdKQGAYQmMLLlo10Jj91/v6OhqDtpTSU2LyebjJZ0JE5xiWjmA+4bPs
+				tgOe+TmaNlQdT47V9whXx2+hKBYMpKtfv9TYhDoxBrQvaCguyVYDcqGyzslzjZonDeVIQQtLQjpR
+				Bi/eLrrmV+0CiPZowfceX9SJEknomc/TrYDRgoZRoIhZh6WG/68h+kzHN9MYDLwxM9vgxifQ5/xe
+				anMfDItZGZ+rtPKLq/yW6glOw//ctmngLwLO/wuyG7/yeJ98sj7bmO2SP52MvKmj6F8dag+m2V8/
+				4n4KYl7KsAIAAw==
+			"
+			;;
+		21)
+			MACHINE="dm520"
+			RECOVERY_KEY="
+				mQENBFcLsf0BCADDo4SxnQwl16cWSYnTwwp+E6ZvdhY3x9yw7b//MUDELtKkEp7wZ+AtHDYd+jzJ
+				Syc+n1m4MkArNUzCdseFJJAYEsNEjZ6ZkoMSQ/GZsIKi2IYT0LXN+9c2ZLLZstNZ2201KwqjFkpE
+				GXSn7VeLAvm82UgMaECY+4vJ5K3XtsLX6onCfidKy4qI8si4CTLylkDegGQ035FlkzqMKA8flafd
+				RGiEWO/2o2ZdYgdjOYQq6W2MaI6zgDzg1V2HMXSweIxnhn8W4iZF80nLTPihoe+p3FRKX0d2G4B0
+				wM49BTgfOgdcu3d3xZBRndOUXq0biga814jYLm3o+DqCmfmt3fsVABEBAAG0NERyZWFtYm94IERN
+				NTIwIFJlY292ZXJ5IDxkbTUyMEByZWNvdmVyeS5kcmVhbWJveC5kZT6JATgEEwECACIFAlcLsf0C
+				GwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJENzmv7ygdoPTTw0IAIN+WQMjAQGbSEo6DP41
+				U8g3u3gRVxBWpAPeE8wsq3wMjmDK4kcCohnWzJSqb7O4XFDUO0fsg0InojpYCIvfhSK+7eohwIaJ
+				ilkdM37nUY7TioFY3pOx63ZzDAJ5SsirU26CIxB+hHWueaS/XsGinodzxl6H9/l8I33U/2DN1oUe
+				y9JcHVNxdBRtSNZMYyZXlA+4LrkDDN6/c6kpIG2uZEYOH0WlP+Mqu9G81yYYKiK9MTlsYHcCoSlV
+				XR8VVsVBxKkfSsoWLMkhE7aEFqq+FeVjcrRyc7R+QGhdzwq9gK50iXpr+YxfHJNn2FML185NGwyp
+				Gnvzh5YpHKnihOS+J7c=
+			"
+			;;
+		22)
+			MACHINE="dm900"
+			RECOVERY_KEY="
+				mQENBFfS0TQBCADLP/mDLWiIF/dJmVFVzQf9CJ7jtb5ilVf4SOasXkPEbdtDsvIIE8ShAHPUgmYC
+				YGAl5FJNxaPZMhyylC9BZOLeYdUgJVRJXjY2WX/bE/6/J5z9UWj+XPzbnbxC+ZnzOGwyUAiHtwbF
+				YLH0SnCN6LEl+nqgwRwpKBgFp64YyAAJ/Rpj5tK6T9v5QuN5CK/UcClmLSqlC/KSbjf93+W9AyOM
+				9F/apxNnhWyEPPjEQbJV8G1WTDL12j4NER3CwwGr+WlKidNdtqDZYYMx89p/qLoV0kbk8tOB7Szx
+				STFQIpetPi++WlKduS5K1gmVYSU8v9WdSAIDujbH1lqOtBq6AaIFABEBAAG0NERyZWFtYm94IERN
+				OTAwIFJlY292ZXJ5IDxkbTkwMEByZWNvdmVyeS5kcmVhbWJveC5kZT6JATgEEwECACIFAlfS0TQC
+				GwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEPAqD3Z9onVhi9YIALa4eA9XRbyNT/kz2fj9
+				gJ9aLfoxPACbkc2pxwVmLtqeCvsgzEvG62QkFwfL+HDQy2G3YgOSYM8/Z1Y8Agp0iS/QNzNE9v7u
+				cniOy7bX+L+M/zZtLnmY4ixIWcPdMraipjaH3v1c9SUg4eeN6WRgQnPmDA2w+PBViXoAAuqKQrG/
+				7DrGLzXiUzRgxoub4hm1au6KSnEgthn7O33dtCKRDwlCFDHNqdOpgayfGKZ+ENrP5FPZIuSmJH+Z
+				GWxsi2P4cmVwsSE0i1REX3pk1xd4lefdmminxhgsrHnlh4q5O6fSrSlIfNKZ3SZZ3KeSCB21g/9L
+				5jAezlvBvp2M0qC2EDQ=
+			"
+			FSBL_KEY="
+				mQENBFhPLT4BCACu7IxjzWdrzWYh0lbFx9AvMmniszx67gAvvz0AMlug25TsVo+2u+YMacK5QX6b
+				8GLkuUYCETZzadaSoOd3WqUadjmtgqa1+G4BZPEHSuyrmMGuathRWCHXJ0dXC7d41ckZS0ufpHM7
+				/a9MBh4sJUdrVrGCvxfRYms/R3CrWJgEcZGgHfeS85XFTAQygALnLtk4j/12am9npLDOFAfxy5D1
+				GOi832omdu+QeCLpBqjCXbYm3C6+Vwpkm/780o0tGAuogKhflsc0C9ax50oEtj/G7xLCoIjcKpxr
+				mX3fh6kxD54mIj0nMSvSJiDkLICDBsKRuOJ+HCrqo0yK5r6LsH2TABEBAAG0NURyZWFtYm94IERN
+				OTAwIChGU0JMIHVwZGF0ZSkgPGRtOTAwQGZzYmwuZHJlYW1ib3guZGU+iQE4BBMBAgAiBQJYTy0+
+				AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBo07UpmBtXLJrCB/4u4tsMBivjsKlrGdvu
+				/QiOO2+CO2XXItfFctyOgUsqIUonYAJK6BUv2rb0wMqSjwGcqjQjqdtefe4aILqZKqjlyneIkyrx
+				J7e/W24g43xo6tVGQuX8RXXEGeN2NaqVL3HUi+BAvPwAqZujQn0RA8VLE8U5KrdAhKm5VxcnHurh
+				AaqnV6GBTmjIqJSLMzIcUAqi4Y1Pv2FfHMYJZetArH0CQFH2BZthhheWj/BvKOSBJUFMcWGpwZeo
+				sPMw9rDJPziwiMhLqFlLip3bk4PU1NSSluTvPyxoVh43P4flCSuvZKZgz/aJ+6IB8O1SYLPRu+51
+				kII48WItRJMlH2Fpur47uQENBFhPLT4BCACyzVlv6Ne3JodR+yihnizl622H8xstIqXVVXnmUwBR
+				rbQg4/NpqtDNEIh1GdhLgE3F+dFMRBlNFsGcHbEhmB9Gn0LNHFjDkKB4/LFqVh2k4aemRF6xafkd
+				kZNwMU390OG21AgxGYoOP/YDqHKEdQ0+H+1qjyIuCu66UwX1U22Y6si9iXhBVXEkv+Ga4b1LMCoX
+				M/664oeU2hey7UcWkiFibJ8E2jLGIu4+8wNBDvt9I+2p6gSlu6xwvUSmpBhU+wo2/+uav7WAb6Ub
+				bpRZ6URvb2F0o2xSJ7FlRYyGGCcOXcLYRQzUt2ataS7th1/NNKmtSUFwCemrQJU9Lpt+NtHPABEB
+				AAGJAR8EGAECAAkFAlhPLT4CGwwACgkQaNO1KZgbVyy4pgf/TVckA31sAHQXwkzvF5rmRo/KqBBL
+				pRtCaY+48l/Ac5aXT1evsjRZKBCkU4QOkJsytP0E3Rj/o8kAcT34uS+7J4xZGdyM+hcR6huA4CDK
+				z6gz3op9mGHF0PIbY7cm6tu+k32iuy+Tp5a3oPywUSkoMw8FT6GwmSf3VADOMR3TdiTP9XRvhgGW
+				qCtHm0s91wOwsYifEDyNLg39QW801YXKup7Gj7E0u8p1c9Ey+Gifio/YrAB4YaJuP0uaM2Mt6OJp
+				kl9JWN12d5M7linrcbpm2/WpzKzSfw5LEtzZSeEO0CaYRwhoYKxUsaMZwMFGtuUDw34RbHDqfpok
+				s3F9cSJ97g==
+			"
+			;;
+		*)
+			abort "Unsupported machine!"
+			;;
+	esac
+
+	case "$MACHINE" in
+		dm520)
+			FLASH_DEVICE="/dev/mtd0"
+			MTD_DEVICE="${FLASH_DEVICE}"
+			UBI_ID="0"
+			UBI_DEVICE="/dev/ubi${UBI_ID}"
+			UBI_VOL_ID="0"
+			FILESYSTEM="ubifs"
+			;;
+		dm820|dm900|dm7080)
+			FLASH_DEVICE="/dev/mmcblk0"
+			MMC_DEVICE="${FLASH_DEVICE}"
+			FILESYSTEM="ext4"
+			;;
+	esac
+
+	case "$MACHINE" in
+		dm520)
+			KERNEL_PARTITION="/dev/mtd2"
+			ROOT_PARTITION="${UBI_DEVICE}_${UBI_VOL_ID}"
+			DATA_PARTITION="/dev/disk/by-label/${DATA_NAME}"
+			KERNEL_SIZE=$((5 * 1024 * 1024))
+			SSBL_SIZE=$((1024 * 1024))
+			;;
+		dm820|dm7080)
+			ROOT_PARTITION="/dev/mmcblk0p1"
+			DATA_PARTITION="/dev/mmcblk0p2"
+			KERNEL_SIZE=$((32 * 1024 * 1024))
+			SSBL_SIZE=$((4 * 1024 * 1024))
+			SGDISK_ARGS="-n 1:147456:2097151 -c 1:rootfs -t 1:8307
+                                     -n 2:2097152: -c 2:data -t 2:8300"
+			PARTED_ARGS="mkpart primary ext2 72MiB 1024MiB
+			             mkpart primary ext2 1024MiB 100%"
+			;;
+		dm900)
+			KERNEL_PARTITION="/dev/mmcblk0p1"
+			ROOT_PARTITION="/dev/mmcblk0p2"
+			DATA_PARTITION="/dev/mmcblk0p3"
+			KERNEL_SIZE=$((31 * 1024 * 1024))
+			SGDISK_ARGS="-n 1:2048:65535 -c 1:kernel -t 1:8301
+                                     -n 2:65536:2097151 -c 2:rootfs -t 2:8307
+                                     -n 3:2097152: -c 3:data -t 3:8300"
+			PARTED_ARGS="mkpart primary ext2 1MiB 32MiB
+			             mkpart primary ext2 32MiB 1024MiB
+			             mkpart primary ext2 1024MiB 100%"
+			;;
+	esac
+
+	case "$MACHINE" in
+		dm520|dm820|dm7080)
+			FSBL_SIZE=$((1024 * 1024))
+			POSTINSTS="dreambox-secondstage kernel-image"
+			;;
+		dm900)
+			FSBL_SIZE=$((3 * 512 * 1024))
+			POSTINSTS="kernel-image"
+			;;
+	esac
+}
 
 is_beneath_directory()
 {
@@ -169,7 +334,14 @@ create_filesystem()
 
 blkdev_has_filesystem()
 {
-	is_blockdev "${1}" && blkid -o export "${1}" | grep -q "^TYPE=${FILESYSTEM}$"
+	is_blockdev "${1}" && (
+		if hash blkid 2>/dev/null; then
+			blkid -o export "${1}" | grep -q "^TYPE=${FILESYSTEM}$"
+		else
+			local dir=`mktemp -d -p ${WORKSPACE}` || abort 'Failed to create temporary mount point'
+			grep -q "^${1}\s[^\s]\+\s${FILESYSTEM}\s" /proc/mounts || (mount -t ${FILESYSTEM} -o ro "${1}" "${dir}" 2>/dev/null && umount "${dir}")
+		fi
+	)
 }
 
 create_nand_filesystem()
@@ -217,10 +389,11 @@ create_ubi_volume()
 create_partition_table()
 {
 	info "Creating partition table"
-	xtrap sgdisk -z \
-		-n 1:2048:65535 -c 1:kernel -t 1:8301 \
-		-n 2:65536:2097151 -c 2:rootfs -t 2:8307 \
-		-n 3:2097152: -c 3:data -t 3:8300 "${1}"
+	if hash sgdisk 2>/dev/null; then
+		xtrap sgdisk -z ${SGDISK_ARGS} "${1}"
+	else
+		xtrap parted --script --align=optimal "${1}" -- mklabel gpt ${PARTED_ARGS}
+	fi
 }
 
 create_tarball()
@@ -306,6 +479,12 @@ fetch()
 {
 	info "Downloading '${1}/${2}'"
 	wget -q "${1}/${2}" -O "${2}" >&3 2>&4
+}
+
+create_keyring()
+{
+	export GNUPGHOME="${WORKSPACE}"
+	echo "${1}" | base64 -d > trustedkeys.gpg || abort 'Failed to write public key'
 }
 
 verify()
@@ -466,8 +645,12 @@ write_lba()
 
 select_boot_source()
 {
-	info "Enabling boot source ${2}"
-	printf "opt${2}\0" | xdd of=${1} bs=512 seek=64
+	case "${MACHINE}" in
+		dm820|dm7080)
+			info "Enabling boot source ${2}"
+			printf "opt${2}\0" | xdd of=${1} bs=512 seek=64
+			;;
+	esac
 }
 
 usage()
@@ -556,3 +739,14 @@ xtrap()
 {
 	(trap '' HUP INT TERM; exec $@) >&3 2>&4
 }
+
+compatible()
+{
+	for m; do
+		[ "$m" != "${MACHINE}" ] || return 0
+	done
+
+	abort "Unimplemented command."
+}
+
+librecovery_init
