restore-settings: fix clobbered permissions of top-level directories

diff --git a/restore-settings b/restore-settings
--- a/restore-settings
+++ b/restore-settings
@@ -28,13 +28,12 @@ if is_beneath_directory "${FILENAME}" "${DATA_MOUNTPOINT}"; then
 fi
 safe_mount "${ROOT_PARTITION}" "${ROOT_MOUNTPOINT}" || abort "Failed to mount root filesystem"
 
-mkdir settings
-extract_tarball "${FILENAME}" settings || abort "Failed to extract settings"
+extract_tarball "${FILENAME}" . -v tmp/.recovery || abort "Failed to extract settings"
 
-if [ -f "settings/tmp/.recovery/backup-paths.bak" ]; then
+if [ -f "tmp/.recovery/backup-paths.bak" ]; then
 	info "Deleting files and directories contained in backup"
 	IFS=$'\n'
-	set -- $(cat settings/tmp/.recovery/backup-paths.bak)
+	set -- $(cat tmp/.recovery/backup-paths.bak)
 	unset IFS
 	for path; do
 		rm -rfv "${ROOT_MOUNTPOINT}${path}"
@@ -42,15 +41,14 @@ if [ -f "settings/tmp/.recovery/backup-paths.bak" ]; then
 fi
 
 info "Restoring configuration files"
-cp -av settings/* ${ROOT_MOUNTPOINT}/
+extract_tarball "${FILENAME}" "${ROOT_MOUNTPOINT}" -v --exclude=tmp/.recovery
 
-if [ -f "settings/tmp/.recovery/pwhash-root.bak" -a -f "${ROOT_MOUNTPOINT}/etc/shadow" ]; then
+if [ -f "tmp/.recovery/pwhash-root.bak" -a -f "${ROOT_MOUNTPOINT}/etc/shadow" ]; then
 	info "Restoring root password"
-	PWHASH=$(cat "settings/tmp/.recovery/pwhash-root.bak")
+	PWHASH=$(cat "tmp/.recovery/pwhash-root.bak")
 	sed -e "s,^\(root:\)[^:]*\(:.*\),\1${PWHASH}\2," -i "${ROOT_MOUNTPOINT}/etc/shadow"
 fi
-if [ -f "settings/tmp/.recovery/packages.bak" -a -d "${ROOT_MOUNTPOINT}/etc/enigma2" ]; then
+if [ -f "tmp/.recovery/packages.bak" -a -d "${ROOT_MOUNTPOINT}/etc/enigma2" ]; then
 	info "Saving list of installed packages"
-	cp -av "settings/tmp/.recovery/packages.bak" "${ROOT_MOUNTPOINT}/etc/enigma2/packages.bak"
+	cp -av "tmp/.recovery/packages.bak" "${ROOT_MOUNTPOINT}/etc/enigma2/packages.bak"
 fi
-rm -rf settings/tmp
